platform :ios, '8.0'

use_frameworks!

target 'temporaryProject_Example' do
  pod 'temporaryProject', :path => 'temporaryProject.podspec'

  target 'temporaryProject_Tests' do
    inherit! :search_paths

    
  end
end
